- hosts: remote
  become: yes
  tasks:
    - name: Check if wget is installed
      shell: yum info wget | grep Repo
      register: wget_repo

    - debug: var=wget_repo

    - name: Install wget
      command: yum install wget -y